from typing import Protocol, Any


class AsyncRepository(Protocol):
    async def execute(self, query: str) -> list[dict[str, Any]]: ...

class AsyncRepositoryFactory(Protocol):
    async def connection(self) -> Any: ...
    async def disconnect(self) -> Any: ...
    async def connect(self) -> AsyncRepository: ...
    