connector:
  dummy_api_1:
    name: dummy_api_1
    type: api
    base_url: https://www.dummy_api_1.co
    timeout: 5
    retry: 3
    auth:
      type: token
      key_name: apikey
      key_value: ${oc.env:API_KEY}

  dummy_api_2:
    name: dummy_api_2
    type: api
    base_url: https://api.dummy_api_2.com
    timeout: 5
    retry: 3
    auth:
      type: basic
      username: ${oc.env:API_USERNAME}
      password: ${oc.env:API_PASSWORD}

  dummy_api_3:
    name: dummy_api_3
    type: api
    base_url: https://api.dummy_api_3.com
    timeout: 5
    retry: 3
    auth:
      type: none
