from typing import Protocol, Any


class AsyncResilientHttpClient(Protocol):
    async def get(self, *args: Any, **kwargs: Any) -> Any: ...
    async def post(self, *args: Any, **kwargs: Any) -> Any: ...
