operation:
  dummy_api_1_op:
    name: market_stock
    connector: ${connector.dummy_api_1}
    endpoint: /query
    method: GET
    parameters:
      function: TIME_SERIES_WEEKLY
      symbol: APL, IBM, MSFT, GOOG

  dummy_api_2_op:
    name: market_stock
    connector: ${connector.dummy_api_2}
    endpoint: /time_series
    method: GET
    parameters:
      symbols: [APL, IBM, MSFT, GOOG]
      interval: 5min
      apikey: demo
      number: 5
      list_numbers:
        - 4
        - 45
        - 45.5